### ISSUE TITLE
Reduce pollution of global namespace

### ISSUE THREAD

**Issue by kjameslubin** [blockapps/blockapps-js#9]
Module exports should read 
```
module.exports = (function () {
  return {
     ... 
  };
})();
```
rather than
```
module exports = { 
      ...
  };
```

**Comment by prashantpawar** [comment]
+1

It was on my radar. How would people feel if we had a style guide? Something like this:

https://google.github.io/styleguide/javascriptguide.xml

**Comment by kjameslubin** [comment]
It is definitely a good idea, and I'm fine with google's (though I may break it myself at times). It's probably time for a Contributing.md also... will throw one together today or tomorrow.

**Comment by kjameslubin** [comment]
BTW, @prashantpawar, is there any sort of Javascript linter that would enforce a style guide?

**Comment by prashantpawar** [comment]
Yes, [jshint](https://github.com/jshint/jshint) is by far the superior choice. If you want, I can integrate it to gulp (on master).

In addition to jshint I would recommend a style enforcer(jshint does not enforce 'style', it only tries to prevent you from getting caught in code smells and pitfalls, like using == instead of ===). Style checker on the other hand enforces a consistent coding style(So reading code is easy):

[Javascript Style Checker](http://jscs.info/)

More info:
http://jscs.info/overview

We can enable the presets of any of the existing [jscs settings](http://jscs.info/rules) (because it's hugely configurable, that's why taking a preset is a good option).

Keep one thing in mind, Javascript is super free form relative to other languages(not to mention this is Open Source project), it results in coding for it being a wild west territory. This is why there are so many pluggable third party solutions to maintain the source code itself(eg testing etc).

If it's possible do check out Typescript(or Coffeescript for that matter), they allow you to avoid the pain of Javascript.

**Comment by ryanreich** [comment]
I don't know if this issue is ever going to be "resolved", but the outcome of my discussion with Kieren about it a while ago is: directly assigning module.exports does not actually pollute the global namespace and I would like to see direct evidence of any claim to the contrary.  Until then, I think the alternative style is quite ugly and would be a lot of work to change to, so I will not do anything about this for now.

**Comment by kjameslubin** [comment]
Since we haven't moved on this and it doesn't look like we will we should probably close
